# This docker compose is used for testing

version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"

services:
  postgres:
    logging: *default-logging
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: nian
      POSTGRES_PASSWORD: nian
      POSTGRES_USER: nian
    #expose:
      #-5432
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nian"]
      interval: 10s
      timeout: 5s
      retries: 5

  nianbot:
    logging: *default-logging
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/nianbot:ro
    tty: true
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres

volumes:
  db-data:
