# This docker compose is used for testing

version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  db:
    << : *logging
    << : *restart_policy
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: nian
      POSTGRES_PASSWORD: nian
      POSTGRES_USER: nian
    #expose:
      #-5432
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nian"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    << : *logging
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot:ro
    tty: true
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
