[tool.poetry]
name = "nianbot"
version = "2.0.0"
description = "The Discord Bot for the KyoStinV official Discord Server."
authors = ["gian <@gian@2222>"]

[tool.poetry.dependencies]
python = "3.10.*"

"discord.py" = "2.1.0"

aiohttp = "3.8.3"
aiodns = "3.0.0"
beautifulsoup4 = "4.11.1"
tldextract = "3.4.0"
markdownify = "0.6.1"
psycopg2 = "2.9.5"

colorama = "0.4.6"
coloredlogs = "15.0.1"
emoji = "2.1.0"

arrow = "1.2.3"
more-itertools = "8.14.0"
python-dateutil = "2.8.2"
python-frontmatter = "1.0.0"
pyyaml = "6.0"
rapidfuzz = "2.11.1"
regex = "2022.9.13"
deepdiff = "5.8.1"

sentry-sdk = "1.9.10"
statsd = "3.3.0"
pydantic = "1.10.2"

[tool.poetry.dev-dependencies]
coverage = "6.5.0"
flake8 = "5.0.4"
flake8-annotations = "2.9.1"
flake8-bugbear = "22.9.23"
flake8-docstrings = "1.6.0"
flake8-string-format = "0.3.0"
flake8-tidy-imports = "4.8.0"
flake8-todo = "0.7"
flake8-isort = "5.0.0"
pep8-naming = "0.13.2"
pre-commit = "2.20.0"
pip-licenses = "3.5.4"
pytest = "7.1.3"
pytest-cov = "4.0.0"
python-dotenv = "0.21.0"
pytest-xdist = "2.5.0"
pytest-subtests = "0.8.0"
taskipy = "1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python -m bot"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
build = "docker build -t ghcr.io/gentilinigian/nianbot:latest -f Dockerfile ."
push = "docker push ghcr.io/gentilinigian/nianbot:latest"
test-nocov = "pytest -n auto"
test = "pytest -n auto --cov-report= --cov --ff"
retest = "pytest -n auto --cov-report= --cov --lf"
html = "coverage html"
report = "coverage report"
isort = "isort ."

[tool.coverage.run]
branch = true
source_pkgs = ["bot"]
source = ["tests"]

[tool.isort]
multi_line_output = 6
order_by_type = false
case_sensitive = true
combine_as_imports = true
line_length = 120
atomic = true

[tool.pytest.ini_options]
# This stops pytest from running functions named `setup` in test files.
addopts = "-p no:nose"
